### ISSUE TITLE
choice_queryset columns are queried only at server (re-)start

### ISSUE THREAD

**Issue by jxrossel** [TriOptima/tri.table#16] opened 2017-06-02 13:39 UTC
Hi,

I've noticed that when defining a `choice_queryset` column the default behaviour is to query the choices data only once, when the app is loaded. In order to query the queryset at each request, one need to give a `lambda` function (like: `choices=lambda table, **_: Status.objects.all()` ). Is that a desired feature ?

In Django forms, the policy is a bit different: for `ModelChoiceField`, the queryset is queried whenever the form is rendered.

**Comment by boxed** [comment] 2017-06-02 18:16
Can you supply a larger example? This seems strange to me. We just store the queryset itself and that is copied when iterating over it I believe.

**Comment by boxed** [comment] 2017-06-30 11:08
I wrote a small test for this and it seems to behave correctly. Is that code you supplied directly from your code or did you tweak it to make it simpler?

**Comment by jxrossel** [comment] 2017-07-04 12:42
Hi,

Sorry for my late answer, I was ill and then on vacation... !

I define a table like this:

```
class ProjectTable(Table):

    # ... other columns defined here

    status = Column.choice_queryset( 
            query__show=True, query__gui__show=True,
            query__value_to_q_lookup='status',
            #choices=lambda table, **_: Status.objects.all(), # <- choice list refreshed every time the page is loaded
            choices=Status.objects.all(), # <- choice list refreshed at server re-start
            model=Status,
            sort_key='status__status',
            )
    class Meta:
        model = Project 
```

The `Status` model is a simple model with a list of status.

The view is:

```
    table = ProjectTable(
            data=Project.objects.can_view( request.user ).select_related( 'status','group' ) )
    
    return render_table_to_response( 
            request, table=table, 
            template='sata/list_generic.html', paginate_by=100,
            context={'url_target':'sata:projects', 
                     'bc_target': _('projects'),
                     'page_title': _('project list') } )
```

This problem is present for Django 1.10 and 1.11

**Comment by boxed** [comment] 2017-07-05 10:37
Well I must have written my previous test all wrong, because I can now reproduce this behavior trivially in django 1.8 and the documentation for django 1.7 makes it quite clear this bug should exist there too. 

This is a great catch! We're working on new major (ie somewhat backwards incompatible) versions of tri.form, tri.query and tri.table to fix some things that where bad, so this is a great thing to fix before that.

Me and @jlubcke discussed briefly if this was a feature and not a bug, but we agreed with your assessment that it's too surprising to be a feature and should be classified as a bug.

**Comment by jxrossel** [comment] 2017-07-05 10:47
Thanks, good to know !

**Comment by boxed** [comment] 2017-08-22 11:52
Fixed in new tri.table 5.0.0!

**Closed** 2017-09-17 18:37 UTC
